#配置数据源
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      maxRequestSize: 500MB
  datasource:
    druid:
      url: jdbc:mysql://10.129.16.218:3306/saleman?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
      username: saleman
      password: saleMan#191021
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 100
      # 获取连接超时时间
      max-wait: 60000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
  redis:
    #数据库索引
    database: 1
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: p54fRKfEIQ
    timeout: 5000
    sentinel:
      nodes: 10.129.2.247:26379,10.129.2.248:26379,10.129.2.249:26379
      master: xukeredis

#明源数据库
mingyuan:
  url: jdbc:sqlserver://10.30.2.84:1433;DatabaseName=dotnet_erp60
  username: myerp
  password: Mysoft!@#123
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

#明源数据库
mingyuan352:
  url: jdbc:sqlserver://10.30.2.84:1433;DatabaseName=dotnet_erp352
  username: myerp
  password: Mysoft!@#123
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

#供销存
gongxiaocun:
  url: jdbc:mysql://10.129.16.214:3306/mars?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
  username: salemanview
  password: Saleman#view1230
  driverClassName:  com.mysql.cj.jdbc.Driver

#非操盘数据库配置
nos:
  url: jdbc:mysql://10.129.16.82:3306/saleprj?characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  username: salemanview
  password: SaleMan#1108
  driverClassName:  com.mysql.cj.jdbc.Driver

#非工程采购系统
mingyuancost:
  url: jdbc:oracle:thin:@10.129.16.103:1521/tenderdb
  username: salemanview
  password: Saleman_1231
  driverClassName: oracle.jdbc.driver.OracleDriver

#旭客
xuke:
  url: jdbc:mysql://10.129.16.202:3306/xuke?characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true
  username: salemanview
  password: Sale#View0330
  driverClassName:  com.mysql.cj.jdbc.Driver

loadIp:
  thisIp: salesmgt.cifi.com.cn
#jwt
jwt:
  header: Authorization
  secret: mySecret-webg
  refresh:
    secret: mySecret-refresh-web
    # token 1440 小时   一个月
    expiration: 1440
  expiration: 2592000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info
  backLogin:
    path: /backLogin
  dingLogin:
    path: /dingLogin

#activemq:
#  user: admin
#  password: admin
#  broker-url: failover:(tcp://10.129.36.25:61616,tcp://10.129.36.26:61616,tcp://10.129.36.27:61616)
#  jms:
#    pub-sub-domain: true
activemq:
  user: admin
  password: admin
  broker-url: failover:(tcp://10.129.0.195:61616,tcp://10.129.0.197:61616,tcp://10.129.0.198:61616,tcp://10.129.0.199:61616)
  pool:
    enabled: true
    max-connections: 10
  alignment: xsgl_queue.oa.approval

queueName: publish.queue
topicName: publish.topic

#如果生产环境要开启swagger，需要配置请求地址
#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: # 接口域名或外网ip

#是否允许生成代码，生产环境设置为false
generator:
  enabled: false

#是否开启 swagger-ui
swagger:
  enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=cswagger-starterountSql

oa:
  host: https://oa.cifi.com.cn
  oaPreviewUrl: https://oa.cifi.com.cn
  sysCode: xsgl
  secretKey: xsgl


# 日志配置  为空为项目跟目录下的logs  或者指定已经存在的目录
log:
  path: /app/tomcat-salman/logs


sso:
  appUser: AUTH_SALEMAN
  privateKey: mqd37gxm3evvljsg
  url: https://sso.cifi.com.cn/siam/api/v2/token/tgt/auth
  tempTokenUrl: https://sso.cifi.com.cn/siam/oauth2.0/accessTokenByJson?client_id=AUTH_SALEMAN&client_secret=mqd37gxm3evvljsg&response_type=code&redirect_uri=http%3A%2F%2Fsalesmgt.cifi.com.cn%2F%23%2Fdashboard&code=
  accessUrl: https://sso.cifi.com.cn/siam/oauth2.0/profileByJson?access_token=



testmingyuan:
  url: https://salesmgt-api.cifi.com.cn/api/public/writedatatobpm

testmingyuanflow:
  url: https://salesmgt-api.cifi.com.cn/Workflow/MTStart2.aspx

resultUrl:
  url: https://salesmgt.cifi-api.com.cn/Workflow/MTStart2.aspx?
#销管发送供销存月度签约计划esb接口地址，账号，密码
testgongxiaocun:
  url: http://esb.cifi.com.cn:8100/v1/sms/signPlan/insert
  #url:  https://mars.cifi.com.cn/api/v1/esbSync/monthTradePlan
  userId: salesmanager01
  password: prod@salesmanager#

testMyApi:
  urlStart: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/CreateResult/
  urlHistory: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/Audit/
  urlEnd: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/ApproveClose/
  adjustmentStart: https://sales-api.cifi.com.cn/api/FyglService/CreateResult/
  adjustmentHistory: https://sales-api.cifi.com.cn/api/FyglService/Audit/
  adjustmentEnd: https://sales-api.cifi.com.cn/api/FyglService/ApproveClose/
  #明源校验费用接口
  SendApproveCheck: https://myfee.cifi.com.cn/service/Mysoft.Fygl.Services.BPMWorkflowServices.BPMWorkflow/SendApproveCheck.aspx
  #售楼接口
  salesOfficeStart: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/CreateResult/
  salesOfficeHistory: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/Audit/
  salesOfficeEnd: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.Common.Plugin.AppServices.BPMWorkFlowAppService/ApproveClose/
#prod文件上传路径
uploadPath:
  /app/netdata
#prod文件下载路径
relepath:
  /netdata

#编制页面路径
organization:
  url: http://salesmgt.cifi.com.cn/#/floatingPriceMy?
#永中文件预览
yongzhongurl: https://oadoc.cifi.com.cn/dcs.web/onlinefile
#风控接口
#mingyuanrisk:
qdfkesb:
  #url: https://face-auth.cifi.com.cn/fk/project-list-esb
  url: http://esb.cifi.com.cn:8115/v1/qdfk/riskManageInfo/query
  userId: salesmanager01
  password: prod@salesmanager#
createTimerisk:
  #url: https://face-auth.cifi.com.cn/project/findProjectCreateTime-esb
  url : http://esb.cifi.com.cn:8115/v1/qdfk/project/query
  userId: salesmanager01
  password: prod@salesmanager#

fkEsbTrade:
  url: https://face-auth.cifi.com.cn/rc/trade-list-esb
  userId: salesmanager01
  password: prod@salesmanager#



#注册xxl-job需要的参数
xxl:
  job:
    admin:
      #注册地址
      addresses: https://job.cifi.com.cn/xxladmin/
    executor:
      #执行器名称
      appname: sman
      ip:
      #端口
      port: 9998
      logpath: /app/ApiLog
      logretentiondays: 30
    accessToken:
DingDing:
  httpIp: https://service.cifi.com.cn/messaging/push/ding_user/272707918
  AgentId: 678522806
  CorpId: ding191e3009d26fae9f
  appkey: dingh8ndeaabytiwuhvo
  appsecret: XAKdj8_YOxcAqZJtgWOYZ21E-7xLOp6f0e7Zv9mvlTxojzIVWgDC8OGCvCzVL-Lo
  accessTokenIp: https://oapi.dingtalk.com/gettoken
  userIdIp: https://oapi.dingtalk.com/user/getuserinfo
  userInfoIp: https://oapi.dingtalk.com/user/get
  messageInfo: https://salesmgt.cifi.com.cn/dingTalkMessage.html
  speedLogoUrl: https://salesmgt.cifi.com.cn/netdata/logo/20200618223519-fd7de0c7-912a-4467-8e2a-0c0120896b08.png?n=%E9%92%89%E9%92%89%E6%8E%A8%E9%80%81_%E9%A6%96%E5%BC%80%E8%8A%82%E7%82%B9%E8%BF%9B%E5%BA%A6%E7%AE%80%E6%8A%A5.png
  warningLogoUrl: https://salesmgt.cifi.com.cn/netdata/logo/20200618220512-4829b840-2a5a-4d14-8f57-b308a1068ce8.png?n=%E9%92%89%E9%92%89%E6%8E%A8%E9%80%81_%E5%AE%9A%E8%B0%83%E4%BB%B7%E9%A2%84%E8%AD%A6%E7%AE%80%E6%8A%A5-3.png
  #定调价预警图片
  pricIngLogoUrl: https://salesmgt.cifi.com.cn/netdata/logo/20200622161423-b89745e9-ae7d-4168-9fe3-eba2fdc69529.png?n=lALPD2sQsWWnHb7NAprNBII_1154_666.png
  #开盘播报图片
  firstBriefingLogoUrl: https://salesmgt.cifi.com.cn/netdata/logo/20200901164136-8875f0c8-360d-4375-a848-3f0e48af5f59.jpg?n=%E5%BC%80%E7%9B%98%E6%92%AD%E6%8A%A55.jpg
  firstBriefingMappUrl: https://salesmgt-uat.cifi.com.cn/openingBoard.html

prcDimProjGoal:
  httpIp: https://service.cifi.com.cn/datacollector/load/prcDimProjGoalMMy
  apikey: 9c82bcfcc52390bf1346106f5d9f3c9f
#钉钉群聊机器人地址
dingTalkRobot:
  url: https://oapi.dingtalk.com/robot/send?access_token=c30bcd22cb1205e3ec8f4136ae5b5605864b0c91f0bf3c65d4408c5bf4b92928
  secret: SEC27663c7c0119f2d2b6e5a104b0895737a33809e5dc0c3e77c36793dfbbb927f5
#旭辉集团邮箱服务器
#测试
emailServer:
  messageHost: https://service.cifi.com.cn
  header: application/x-www-form-urlencoded
Pricing:
  Pcinfourl: https://oa.cifi.com.cn/front/#/reviewApproval/
  mobileInfoUrl: https://oa.cifi.com.cn/mobile/view/bpm/getProcessRun.html
oaflow:
  fpFlowCode: skcslc


syncStageData:
  url: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.ProjectPrep.Plugin.AppServices.ProjectApiAppService/SyncPolicy
  #电商政策申请数据同步明源
  dsPolicyUrl: https://sales-api.cifi.com.cn/api/service/Mysoft.Slxt.ProjectPrep.Plugin.AppServices.ProjectApiAppService/SyncCommerceCompany
  userId: salesmanager01
  password: uat@salesmanager#
firstOpenSystemUrl : http://salesmgt.cifi.com.cn/#/planWrite

#流程结束回调人脸风控系统地址
faceSysCallback:
  url: https://face-sys.cifi.com.cn/oa/callBack
#签约后变更神批表单查询调用明源链接明源
obtainJsonID:
  urlOne: http://sales.cifi.com.cn:9060/PubPlatform/Nav/Login/SSO/Login.aspx?UserCode=admin&Password=4076f862096d1536b6cac6866e386685&PageUrl=http%3a%2f%2fsales.cifi.com.cn%3a9060%2fapi%2fMysoft.Map6.FileManager.AppServices.FileManagerAppService
  urlTwo: https://sales.cifi.com.cn/PubPlatform/Nav/Login/SSO/Login.aspx?UserCode=admin&Password=4076f862096d1536b6cac6866e386685&PageUrl=https%3a%2f%2fsales.cifi.com.cn%2fapi%2fMysoft.Map6.FileManager.AppServices.FileManagerAppService
  fileUrlOld: http://sales.cifi.com.cn:9020
  fileUrlNew: https://myfee.cifi.com.cn
#定调价,获取定调价前C1定稿版
pricingC1:
  controlDateUrl: https://biboard.cifi.com.cn/api/cdr/common/monthlyReport
  dtjqHzUrl: https://service.cifi.com.cn/datacollector/load/prcJyxlProjJyxlStrc?params={},{},{},0,0&apikey=9c82bcfcc52390bf1346106f5d9f3c9f
#薇链接口参数
Vlink:
  #平台地址
  url: https://tcloud.myviding.com/tap/api/gateway/service
  #旭辉appid
  groupId:
  appId: 86605b57528c371ddc4be13b1f28f88a
  appName: 旭辉
  #旭辉私钥
  appPriKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJUwb0ZXSFBaVSp3u+MPRqdoOUeiyqAinTSm/6KRSNIiDRFudaozD7DZlJl9qb8mXAPoL9zKO2NhXEXOWeItCmoV1UIz4rHh067/ml94AXwT7hpQNbWLkR67nI7IjT5TJHzu0NLzH1qx30dYbT7J9zCMR7ucmJT3MrWGhooc1yTFAgMBAAECgYA2B9eU+xFmgICto7V5M1QcVwO/rPaDbmXO5thYURO1fr2K3Z1hqaJ6IyLNQBSU9NiIVbPX26oMgPtBEM2+ux804Fwl2fU0EuKCiQapxtF1l2CkPuTO5ObJkFVbzIZvnFNNDakIT9I3iIoFB+QPemQ1u5S3mv8y7x7Kz7+E3Q6q1QJBAPu28mQ5pltESGVoXmcVTbuFBmaRsFLz1Pqo3vIHf5atmuVPu/XjoZ8WmAoN4s9jpJimvG5QNAZ4lL0nGb6fcasCQQCXuqYpK7bS+JF1iw2zqpaidoVZ/A5ZWkVqomHj+wRkqJGhNH1Y/iovrw06wJE+q5N1+E42DPMrk74GwEGP+jNPAkEAg3KWQiCY7zBJXiuSoOJPJY3iOc369la+8eceBeZEirs+GGH7Ff05eYqi+x0lRIgUfGMWI8VeZcKyadTxbMp24QJBAIeV304DJki4nyNuszvOQPXE+71BpIDsTgPQP7G+alqY2Co6AZk45vHdd/D8i854/Dj7PsjGIbbbO4BE5VGHv7kCQQCQIXjDicfr73ogPdSWqmb8oRJZa2KFqN9VWv0FZgcvqy3P/3dnxYg54AraoyNSAiIH0fsX3zPUb8Sroj7WTkiD
  #旭辉公钥
  appPubKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVMG9GV0hQWlUqd7vjD0anaDlHosqgIp00pv+ikUjSIg0RbnWqMw+w2ZSZfam/JlwD6C/cyjtjYVxFzlniLQpqFdVCM+Kx4dOu/5pfeAF8E+4aUDW1i5Eeu5yOyI0+UyR87tDS8x9asd9HWG0+yfcwjEe7nJiU9zK1hoaKHNckxQIDAQAB
  #平台公钥
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUQUvOrI7z+shO6ULDywzPYEhmrTD5GgE/nUEToXeSe8EM5LGQreZ/OTQ3SwLagX+0mOk3hOEe6zIWRt0yhqKGzvM0XIwRgrghwpkA4ILJGJzQCjZ5sPLoHKM8642SadnOKRK9uPTufSdGyY4XMHgsZTvpzM1POoQn9T9fp7kKgwIDAQAB
  #薇链回调接口
  callBackVlink: https://salesmgt-api.cifi.com.cn/VlinkDocking/callBackVlink

#对接投资系统
dockingInvestment:
  #货值接口
  supplyPlanDataValueUrl: https://iems.cifi.com.cn/invmode/esb/versionExtn/supplyPlanDataValue
  #时间节点和销售目标接口
  salesTargetUrl: https://iems.cifi.com.cn/invmode/esb/versionExtn/salesTarget


#获取非工程采购数据
#http://wiki.cifi.com.cn/pages/viewpage.action?pageId=19988521
nonProjectPur:
  url: http://esb.cifi.com.cn:8083/v1/nonprojectpur/supplier/query
  userId: salesmanager01
  password: prod@salesmanager#
